### ISSUE TITLE
Update FOB flags for new loadouts

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/addons#34]
The FOB flags are determined using factions uniforms. These need updating as existing factions may have had their uniforms changed and new factions are being added.

**Comment by abelarno** [comment]
Done

**Comment by Fourjays** [comment]
Uniforms listed need to match those in the loadouts (https://github.com/blackwatchint/modpack/tree/develop/[BWI]Template.vr/BWI/loadouts), some of which have changed (e.g. PMC).

Flags/cases still need to be added for the following factions:
- [ ] Denmark
- [ ] Finland (x2)
- [ ] Israel
- [ ] Norway (x2)
- [ ] SAS (x3)
- [ ] SFOD-D (x5)
- [ ] Spetsnaz (x2)
- [ ] Sweden (x2)
- [ ] US Army 93
- [ ] USMC 18 (x2)
- [ ] USSR (x2)

**Comment by Fourjays** [comment]
Confirm changes have been applied. Closing.
