### ISSUE TITLE
Investigate creating crates for static weapon ammo resupply

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/addons#4]
Most static weapons require ammo reloaded from an ACE resupply enabled truck. The reloading must be done one magazine at a time by the person using the weapon (ammo can not be stored or stacked). Having a crate that behaves like the resupply truck would make this process more streamlined.

**Comment by TheGrandVizier** [comment]
If this is indeed done via Ace, and "like a truck", I am fairly certain that in ace settings one can choose how many "boxes" / "Shells" etc are "carried" in each batch. No?

**Comment by Fourjays** [comment]
As far as I know the player can't choose. It is always one round/missile/box/magazine.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
