### ISSUE TITLE
Investigate addition of new weather effects

### ISSUE THREAD

**Issue by Fourjays** [blackwatchint/addons#9]
We have long wanted to look into expanding our current selection of weather options. Possibilities previously discussed were sandstorms and snowstorms.

Continuation of blackwatchint/modpack#107.

**Comment by adios113** [comment]
While developing my Zeus addon "Crow", weather module was one of the features which were partialy implemented in it:

**Dynamic Fog Changer:**
- Changes the fog Density, Height, Strenght in real time while using the slider.

**Desert Storm:**
- Post processing effects script with some wind sfxs, to simulate a desert storm. We ran this once on one of my missions, people liked it.

**Snow Storm:**
- Not completed yet, but got a working prototype not included in my mod.

**Thunder:**
- More immersive thunder with more sfx's and post processing effects. Not included in the latest Crow build yet.

Surprisingly, MCC had some nice weather effects and modules, which we could port into our addon.

**Comment by Fourjays** [comment]
Issue no longer relevant due to modpack reset.
